name       : libdnet
version    : 1.12
release    : 1
source     :
    - https://github.com/dugsong/libdnet/archive/libdnet-1.12.tar.gz : b6360659c93fa2e3cde9e0a1fc9c07bc4111f3448c5de856e095eb98315dd424
license    : BSD-3-Clause
component  : system.utils
summary    : libdnet
description: |
    libdnet provides a simplified, portable interface to several low-level networking routines, including network address manipulation, kernel arp(4) cache and route(4) table lookup and manipulation, network firewalling, network interface lookup and manipulation, IP tunnelling, and raw IP packet and Ethernet frame transmission.
builddeps  :
     - pyrex
     - pkgconfig(python-2.7)
setup      : |
    %patch -p0 < $pkgfiles/0001-pyrex2.7.patch
    autoreconf -I config --force --install
    %configure --disable-static
build      : |
    pyrexc python/dnet.pyx
    %make
install    : |
    %make_install
